CLASS zdemo0602 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zdemo0602 IMPLEMENTATION.
METHOD IF_OO_ADT_CLASSRUN~MAIN.
out->write( 'Hello world!' ).
ENDMETHOD.
ENDCLASS.
